### ISSUE TITLE
support multiple version-files

### ISSUE THREAD

**Issue by WouterVH** [4teamwork/ftw.recipe.checkversions#5]
specifying multiple version-files would be handy:

```
  [checkversions-pypi-public]
  # cfr. https://pypi.python.org/pypi/ftw.recipe.checkversions
  recipe = ftw.recipe.checkversions
  versions =
      buildout/versions.cfg
      buildout/base-versions.cfg
  blacklists =
  blacklist-packages =
  index =
      https://pypi.python.org/simple/
  
  
  [checkversions-pypi-internal]
  # cfr. https://pypi.python.org/pypi/ftw.recipe.checkversions
  recipe = ftw.recipe.checkversions
  versions =
      buildout/versions.cfg
      buildout/base-versions.cfg
  blacklists =
  blacklist-packages =
  index =
      ${buildout:index}
```

**Comment by WouterVH** [comment]
note that having two parts does not work. The last part "wins".

it would be nice if the name of the generated script is taken from the partname:
bin/checkversions-pypi-internal
bin/checkversions-pypi-public

**Comment by jone** [comment]
I think it shouldn't be that hard to support multiple version files. The easiest way would probable be to read and concatenate them in the [main command](https://github.com/4teamwork/ftw.recipe.checkversions/blob/master/ftw/recipe/checkversions/command.py#L10).

The `bin/checkversions` name is currently [hard coded in the recipe](https://github.com/4teamwork/ftw.recipe.checkversions/blob/master/ftw/recipe/checkversions/recipe.py#L11), I'm not sure why. I remember there was a reason (maybe I couldn't access the part name), but I don't remember.

I'll not have the time to implement this in the next days, but if you want to do it I'll happily accept pull requests :wink:

**Comment by WouterVH** [comment]
It seems this use-case is already covered if you just use the toplevel  "buildout.cfg" is your versions-file:

```
  [checkversions-pypi-public]
  # cfr. https://pypi.python.org/pypi/ftw.recipe.checkversions
  recipe = ftw.recipe.checkversions
  versions =
      buildout.cfg
  blacklists =
  blacklist-packages =
  index =
      https://pypi.python.org/simple/
```

This will automatically find all [versions]-sections in from all extended profiles.
I did not check how this interacts with blacklisting.
